services:
  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis:8.0.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
 
 
  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq:3.13.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: Admin
      RABBITMQ_DEFAULT_PASS: admin@12345
      RABBITMQ_DEFAULT_VHOST: trainee_management_vhost
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
 
 
  mysql:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql:8.0.41
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trainee_management_db      
    volumes:
      - mysql-data:/data
 
  # api:
  #   # build:
  #   #   context: .
  #   #   dockerfile: ./docker/Dockerfile
  #   #   args:
  #   #     DOMAIN_OWNER: ${DOMAIN_OWNER}
  #   #     NUGET_REPO_NAME: ${NUGET_REPO_NAME}
  #   #     CODEARTIFACT_AUTH_TOKEN: ${CODEARTIFACT_AUTH_TOKEN}
  #   #     REGION: ${REGION}
  #   # image: test
  #   env_file:
  #     - ./CommonLibrary/.env
  #   container_name: trainee-api
  #   depends_on:
  #     - mysql
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   restart: on-failure
 
volumes:
  mysql-data:
  rabbitmq_data: