services:
  mysql: 
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql
    container_name: mysql
    ports:
      - "5000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trainee_management_db
    volumes:
      - mysql_data:/var/lib/mysql
  
  redis: 
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # trainee-management-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql
  #   environment:
  #     - Key=AQAAAAIAAYagAAAAEPuOIWp45kIw+I8GxlJNGsNNSunoQHr4AHFwd6oSqvx15QNJl6dUAmWxQ9d7N2xErg=
  #     - DefaultConnection=server=mysql;port=3306;database=trainee_management_db;user=root;password=root;
  #     - RedisConnectionString=redis:6379
    
volumes:
  mysql_data: